language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t vkathiriya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vkathiriya/docker-react npm run test